tasks:
  - name: Solana
    command: sh -c "$(curl -sSfL https://release.solana.com/v1.10.8/install)" && export PATH=~/.local/share/solana/install/active_release/bin:$PATH && 
    git clone https://github.com/metaplex-foundation/metaplex.git ~/metaplex &&
    yarn install --cwd ~/metaplex/js/ && 
    npm i -g ts-node && npm i -g typescript && ts-node --version &&
    ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts --version
    
    
    
  - name: Tsnode
    command: npm i -g ts-node && npm i -g typescript && ts-node --version
    